#!/usr/bin/env python3
"""log.py — append to, query, check and render the exchange log (rule R4).

    python3 05_tools/log.py add --date 2026-08-18 --dir in --party "ACME" \
        --type letter --doc "Notice of delay" --ref "ACME-L-0142" \
        --path 03_exchange/received/ACME/2026-08-18_notice-of-delay.pdf \
        --thread delay-claim --action open --due 2026-09-01
    python3 05_tools/log.py add --date 2026-08-25 --dir out --party "ACME" \
        --type letter --doc "Reply to notice of delay" --ref "T-0031" \
        --path 03_exchange/issued/ACME/L-0088.pdf --thread delay-claim --answers 12
    python3 05_tools/log.py add --date 2026-09-02 --dir out --party "ACME" \
        --type report --doc "Method statement" --rev C \
        --path 03_exchange/issued/ACME/MS-004-C.pdf --supersedes 15
    python3 05_tools/log.py query --action open            # what is owed, either way
    python3 05_tools/log.py query --party ACME --dir in --since 2026-01-01
    python3 05_tools/log.py set 41 --action closed
    python3 05_tools/log.py check                          # the log against the tree
    python3 05_tools/log.py render                         # rewrite LOG.md

On Windows use `py -3` in place of `python3`.

Why the log is two files
------------------------
`03_exchange/LOG.jsonl` is the record: one JSON object per line, one line per
event, in the order they were written. `03_exchange/LOG.md` is a rendered view
of it, regenerated by this script.

A contract that runs for two years produces thousands of these rows. A markdown
table stops being usable long before that — it cannot be filtered, sorted or
counted, and every hand-edit risks mangling a column. JSONL can be queried in
one pass, by this script or by an agent reading it directly, and it stays
diffable and human-legible in a text editor. The markdown view exists so the log
is still readable by someone with no tools at all.

Both files live in a frozen zone. They are exempt from R1's no-edit rule in
one specific way: rows are added, and a row's `status`, `action`, `due` and
`note` may be updated in place through `set` — which records every change in
the row's `history`. Nothing else about a row is ever rewritten. A row that was
wrong is corrected by a new row, with a note. Rendering preserves anything you
write in LOG.md outside the generated block.

What a row is
-------------
One row per **event**: a document arrived, or a document left. A revision that
was superseded keeps its row; the new revision gets its own. A transmittal
that brought thirty drawings can be one row whose `path` is the folder they
were filed in, or thirty rows if each drawing's revision has to be tracked —
the project decides, and the register (R11) is where a series is followed.

Fields
------
id          assigned on append, never reused; cite it as #12
date        ISO date of the EVENT — sent or received — never of typing it up.
            Required, and must be a real calendar date. If neither the document
            nor the user states it, the row waits: a guessed date is worse than
            no row, because it looks like a fact.
recorded    when the row was written (UTC), set by the script
backfilled  true when the row was written from the documents after the fact
            (--backfilled) rather than at the moment of the event. Permitted;
            marked, so it is never mistaken for a contemporaneous entry.
dir         in | out
party       who it came from or went to, by the label in PARTIES.md
type        letter | drawing | boq | report | po | vo | instruction | submittal |
            minutes | transmittal | invoice | programme | email | contract |
            amendment | notice | rfi | application | certificate | claim | other
            (open set — an unlisted type is accepted with a warning)
doc         what the document is, in words, or its title
ref         the document's own number, or how it arrived (`email (transcript)`)
rev         the sender's revision, not an internal one
thread      the topic or negotiation, matching a context md in datasets/
path        repo-relative path to the filed document, or to the folder holding a
            multi-file event. For an issued document, the PDF — its source sits
            beside it under the same stem (R10).
status      the state of the DOCUMENT: current | superseded by #n | withdrawn
action      what is OWED on it: (blank) | open | answered by #n | closed.
            On an `in` row `open` means we owe a reply; on an `out` row, they do.
due         ISO date the open action is due, if one is set
note        anything that does not fit a column
history     every change made by `set`: field, from, to, when

`status` and `action` are separate because they answer different questions. An
issued letter that asks something is `current` and `open` at once; when the
answer arrives it stays `current` and becomes `answered by #n`; when the next
revision goes out it becomes `superseded by #n` whether or not it was answered.
One column cannot hold both, and the log used to try.

What `add` refuses, and what it merely flags
--------------------------------------------
Refused (nothing is written): a date that is not a real calendar date; a
status or action outside the vocabulary; a path that is absolute or escapes
the repository; a path under 03_exchange/ whose received/issued folder does not
match --dir, or whose party folder does not match --party (direction and party
are lookups, R1 — the row and the tree must agree); a path that points at
nothing, unless --pending says the file is genuinely still on its way; a
--supersedes or --answers id that does not exist. All of it is checked before
anything is written, and the new row and the rows it changes are written in
one atomic replacement — a failed add leaves the log exactly as it was.

Flagged (written, with a warning): a type outside the usual list; a party
label not in PARTIES.md; superseding a row that is already superseded, or of a
different party; answering a row that is not open, or that is in the same
direction. Warnings are for the human; they never change what was written.

`check` reads the whole log against the tree and reports what does not add up:
duplicate ids, dangling #n references, paths that point at nothing, rows and
folders that disagree, party labels not in PARTIES.md, open actions past their
due date, and — the one that matters most — files in 03_exchange/received/,
03_exchange/issued/ or 01_contract/ that no row mentions. A row covers its
path, everything under it if the path is a folder, and any sibling under the
same stem — the source filed beside an issued PDF (R10). Run it at session
start; it is the log read by its gaps.

One writer at a time. The log is a file in a synced folder; two machines
appending at the same moment produce a sync-conflict copy, which the
session-start scan reports (CONFLICT?), and possibly a duplicated id, which
`check` reports. Neither is silent, and neither is worth a locking scheme.
"""

import argparse
import json
import os
import posixpath
import re
import sys
from datetime import date as _date, datetime, timezone

LOG_DIR = "03_exchange"
JSONL = os.path.join(LOG_DIR, "LOG.jsonl")
MARKDOWN = os.path.join(LOG_DIR, "LOG.md")
PARTIES = os.path.join("00_AI_context", "PARTIES.md")

EXCHANGE = "03_exchange/"
CONTRACT = "01_contract/"
# Zones in which every file is expected to have a row (R4). 02_basis/ is not
# one: reference material nobody sent has no direction and no party.
LOGGED_ZONES = ("03_exchange/received/", "03_exchange/issued/", CONTRACT)

BEGIN = "<!-- LOG:BEGIN — generated by 05_tools/log.py; edits here are lost -->"
END = "<!-- LOG:END -->"

FIELDS = ("id", "date", "recorded", "backfilled", "dir", "party", "type", "doc",
          "ref", "rev", "thread", "path", "status", "action", "due", "note",
          "history")
# Columns worth a place in the rendered table. The rest stay in the JSONL,
# where they are still queryable — a fourteen-column markdown table is
# unreadable. Status and action share one column in the view.
COLUMNS = (("date", "Date"), ("dir", "Dir"), ("party", "Party"),
           ("type", "Type"), ("doc", "Document"), ("rev", "Rev"),
           ("ref", "Ref"), ("thread", "Thread"))

DIRECTIONS = ("in", "out")
# Not a closed set — an unlisted type is accepted with a warning, because a
# real project always turns up a document class nobody anticipated.
KNOWN_TYPES = ("letter", "drawing", "boq", "report", "po", "vo", "instruction",
               "submittal", "minutes", "transmittal", "invoice", "programme",
               "email", "contract", "amendment", "notice", "rfi", "application",
               "certificate", "claim", "other")
STATUS_RE = re.compile(r"^(current|superseded by #\d+|withdrawn)$")
ACTION_RE = re.compile(r"^(|open|answered by #\d+|closed)$")
STATUS_HELP = "current | 'superseded by #n' | withdrawn"
ACTION_HELP = "open | 'answered by #n' | closed | '' (nothing owed)"
REF_RE = re.compile(r"#(\d+)")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

# Files the tree may contain beside the documents; `check` expects no row for
# these. Mirrors update_index.py's skip rules.
SKIP_PREFIXES = ("~", ".")
SKIP_SUFFIXES = (".tmp", ".partial", ".crdownload")
SKIP_NAMES = {"desktop.ini", "Thumbs.db"}


# --------------------------------------------------------------------------
# storage
# --------------------------------------------------------------------------

def repo_root(arg=None):
    if arg:
        return os.path.abspath(os.path.expanduser(arg))
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def now_ts():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def valid_date(value):
    if not DATE_RE.match(value or ""):
        return False
    try:
        _date.fromisoformat(value)
    except ValueError:
        return False
    return True


def load(root):
    """Read the JSONL, tolerating blank lines. A bad line is fatal, loudly.

    Silently dropping an unparseable row would lose an event, which is the one
    thing this file exists to prevent.
    """
    path = os.path.join(root, JSONL)
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as e:
                sys.exit(f"{JSONL}:{n} is not valid JSON ({e}).\n"
                         f"Fix the line by hand — do not delete it.")
            if not isinstance(row, dict):
                sys.exit(f"{JSONL}:{n} is not a JSON object.\n"
                         f"Fix the line by hand — do not delete it.")
            rows.append(row)
    return rows


def normalise(row):
    out = {}
    for k in FIELDS:
        if k == "backfilled":
            out[k] = bool(row.get(k, False))
        elif k == "history":
            out[k] = list(row.get(k) or [])
        else:
            v = row.get(k, "")
            out[k] = v if v is not None else ""
    return out


def atomic_write(path, text):
    """Write the whole file, then swap it in. A crash mid-write leaves the old
    file intact rather than a truncated record."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def write_all(root, rows):
    text = "".join(json.dumps(normalise(r), ensure_ascii=False) + "\n"
                   for r in rows)
    atomic_write(os.path.join(root, JSONL), text)


def row_id(row):
    try:
        return int(row.get("id") or 0)
    except (TypeError, ValueError):
        return 0


def next_id(rows):
    return max((row_id(r) for r in rows), default=0) + 1


def by_id(rows):
    return {row_id(r): r for r in rows}


def esc(value):
    """Keep a pipe or a newline in a field from breaking the markdown table."""
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def party_labels(root):
    """Labels from the Register table in PARTIES.md, or None if there is no
    such file. Parsed loosely: the first cell of every table row under the
    `## Register` heading, minus the header and separator rows."""
    path = os.path.join(root, PARTIES)
    if not os.path.exists(path):
        return None
    labels, in_register = set(), False
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                in_register = line.strip().lower().startswith("## register")
                continue
            if not (in_register and line.lstrip().startswith("|")):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            label = cells[0] if cells else ""
            if not label or label.lower() == "label" or set(label) <= set("-: "):
                continue
            labels.add(label)
    return labels


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------

def norm_path(value):
    value = (value or "").strip().replace("\\", "/")
    if not value:
        return ""
    value = posixpath.normpath(value)
    return "" if value == "." else value


def path_problems(root, path, dir_, party, pending=False):
    """Why a path cannot go on a row with this direction and party.

    Direction and party are lookups (R1): received/ is theirs, issued/ is
    ours, and the party folder is the party's label. A row that says otherwise
    is wrong in exactly the way the tree exists to make impossible.
    """
    problems = []
    if (os.path.isabs(path) or re.match(r"^[A-Za-z]:", path)
            or path == ".." or path.startswith("../")):
        return [f"--path must be repo-relative and inside the repository — "
                f"got '{path}'"]
    if path.startswith(EXCHANGE):
        parts = path.split("/")
        if len(parts) < 4 or parts[1] not in ("received", "issued"):
            problems.append(f"a path under {EXCHANGE} must be "
                            f"{EXCHANGE}received/<party>/… or "
                            f"{EXCHANGE}issued/<party>/… — got '{path}'")
        else:
            want = "received" if dir_ == "in" else "issued"
            if parts[1] != want:
                problems.append(f"--dir {dir_} but the path is under "
                                f"{EXCHANGE}{parts[1]}/ — direction is the "
                                f"folder (R1); one of them is wrong")
            if parts[2] != party:
                problems.append(f"--party '{party}' but the path is under "
                                f"{EXCHANGE}{parts[1]}/{parts[2]}/ — the label "
                                f"and the folder must agree (PARTIES.md)")
    if not pending and not os.path.exists(os.path.join(root, path)):
        problems.append(f"no file at '{path}' — file it first (the procedure "
                        f"moves, then logs), or pass --pending and fill the "
                        f"path later with `set <id> --path`")
    return problems


def validate_add(root, args, rows):
    problems, warnings = [], []
    if not valid_date(args.date):
        problems.append(f"--date must be a real ISO date (YYYY-MM-DD), "
                        f"got '{args.date}'")
    if args.due and not valid_date(args.due):
        problems.append(f"--due must be a real ISO date, got '{args.due}'")
    if args.dir not in DIRECTIONS:
        problems.append(f"--dir must be one of {', '.join(DIRECTIONS)}")
    if not STATUS_RE.match(args.status):
        problems.append(f"--status must be {STATUS_HELP} — got '{args.status}'")
    if not ACTION_RE.match(args.action):
        problems.append(f"--action must be {ACTION_HELP} — got '{args.action}'")
    if args.due and args.action != "open":
        warnings.append("--due given without --action open — a due date on "
                        "nothing owed")
    if args.type and args.type not in KNOWN_TYPES:
        warnings.append(f"'{args.type}' is not one of the usual types "
                        f"({', '.join(KNOWN_TYPES)}) — recorded as given")

    path = norm_path(args.path)
    if path:
        problems += path_problems(root, path, args.dir, args.party, args.pending)
    elif not args.pending:
        problems.append("--path is required: a row that points at nothing is "
                        "the drift the log exists to prevent. Pass --pending "
                        "if the file genuinely has not landed yet, and fill it "
                        "with `set <id> --path`.")

    known = by_id(rows)
    for value, name in ((args.supersedes, "--supersedes"),
                        (args.answers, "--answers")):
        if value is not None and value not in known:
            problems.append(f"{name} #{value}: no such event")
    if args.supersedes in known:
        t = known[args.supersedes]
        if (t.get("status") or "").startswith("superseded"):
            warnings.append(f"#{args.supersedes} is already "
                            f"'{t.get('status')}' — superseding it again")
        if t.get("dir") != args.dir or t.get("party") != args.party:
            warnings.append(f"#{args.supersedes} is {t.get('dir')} "
                            f"{t.get('party')}; this row is {args.dir} "
                            f"{args.party} — a revision normally supersedes "
                            f"the same document to the same party")
    if args.answers in known:
        t = known[args.answers]
        if (t.get("action") or "") != "open":
            warnings.append(f"#{args.answers} is not open (action "
                            f"'{t.get('action') or ''}') — answering it anyway")
        if t.get("dir") == args.dir:
            warnings.append(f"#{args.answers} is also {args.dir} — an answer "
                            f"normally goes the other way")

    labels = party_labels(root)
    if labels is not None and args.party not in labels:
        warnings.append(f"'{args.party}' is not a label in {PARTIES} — add the "
                        f"party there first if it is new; labels are permanent")
    return problems, warnings, path


def dangling(value, known):
    return [f"#{m}" for m in REF_RE.findall(str(value or ""))
            if int(m) not in known]


# --------------------------------------------------------------------------
# render
# --------------------------------------------------------------------------

def status_cell(r):
    text = esc(r.get("status"))
    action = esc(r.get("action"))
    if action:
        text += f" · {action}"
        if action == "open" and r.get("due"):
            text += f" (due {esc(r.get('due'))})"
    return text


def render_table(rows):
    if not rows:
        return ["_No entries yet._", ""]
    head = ["#"] + [label for _, label in COLUMNS] + ["Status"]
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    backfilled = False
    for r in rows:
        cells = [f"{r.get('id', '')}"]
        for key, _ in COLUMNS:
            cell = esc(r.get(key))
            if key == "date" and r.get("backfilled"):
                cell += " †"
                backfilled = True
            cells.append(cell)
        cells.append(status_cell(r))
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    if backfilled:
        out += ["† backfilled — written from the documents after the event, "
                "not at the time (R4).", ""]
    return out


def outstanding_lines(rows):
    def key(r):
        return (r.get("due") or "9999-99-99", r.get("date") or "", row_id(r))

    def line(r):
        due = f" — due {esc(r.get('due'))}" if r.get("due") else ""
        thread = f" ({esc(r.get('thread'))})" if r.get("thread") else ""
        return (f"- **#{r.get('id')}** {esc(r.get('date'))} "
                f"{esc(r.get('party'))}: {esc(r.get('doc'))}{thread}{due}")

    open_rows = [r for r in rows if (r.get("action") or "") == "open"]
    we_owe = sorted((r for r in open_rows if r.get("dir") == "in"), key=key)
    they_owe = sorted((r for r in open_rows if r.get("dir") == "out"), key=key)
    body = ["## Outstanding", ""]
    if not open_rows:
        body += ["Nothing open.", ""]
        return body, 0
    body += ["Events whose action is still `open` — what is owed, in either",
             "direction. This is the progress-meeting question, so it is",
             "derived rather than maintained. Run `log.py check` for what is",
             "past its due date.", ""]
    body += ["### We owe a reply", ""]
    body += [line(r) for r in we_owe] or ["- nothing"]
    body += ["", "### They owe a reply", ""]
    body += [line(r) for r in they_owe] or ["- nothing"]
    body.append("")
    return body, len(open_rows)


def render(root, quiet=False):
    """Rewrite the generated block of LOG.md, leaving the rest of it alone."""
    rows = sorted(load(root), key=lambda r: (r.get("date", ""), row_id(r)))
    body = [BEGIN, ""]
    body += [f"{len(rows)} event(s). Generated from `LOG.jsonl` by "
             f"`05_tools/log.py`. Add rows with `log.py add` — hand-editing "
             f"this table changes nothing, because the JSONL is the record.",
             ""]
    body += render_table(rows)
    lines, n_open = outstanding_lines(rows)
    body += lines
    body.append(END)

    path = os.path.join(root, MARKDOWN)
    existing = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            existing = f.read()
    block = "\n".join(body)
    if BEGIN in existing and END in existing:
        pre = existing.split(BEGIN)[0]
        post = existing.split(END, 1)[1]
        text = pre + block + post
    else:
        # No markers: the file is a fresh template or was replaced. Keep
        # whatever prose is there and put the block at the end.
        text = (existing.rstrip() + "\n\n" + block + "\n") if existing else block + "\n"
    atomic_write(path, text)
    if not quiet:
        print(f"{MARKDOWN} rendered — {len(rows)} event(s), {n_open} open.")
    return 0


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_add(root, args):
    rows = load(root)
    problems, warnings, path = validate_add(root, args, rows)
    if problems:
        sys.exit("Cannot log this event — nothing was written:\n  "
                 + "\n  ".join(problems))
    ts = now_ts()
    row = {"id": next_id(rows), "date": args.date, "recorded": ts,
           "backfilled": bool(args.backfilled), "dir": args.dir,
           "party": args.party, "type": args.type, "doc": args.doc,
           "ref": args.ref, "rev": args.rev, "thread": args.thread,
           "path": path, "status": args.status, "action": args.action,
           "due": args.due, "note": args.note, "history": []}
    known = by_id(rows)
    changed = []
    if args.supersedes is not None:
        t = known[args.supersedes]
        apply_change(t, "status", f"superseded by #{row['id']}", ts)
        changed.append(f"#{args.supersedes} → superseded by #{row['id']}")
    if args.answers is not None:
        t = known[args.answers]
        apply_change(t, "action", f"answered by #{row['id']}", ts)
        changed.append(f"#{args.answers} → answered by #{row['id']}")
    rows.append(row)
    write_all(root, rows)          # one atomic write: the row and its effects
    for w in warnings:
        print(f"warning: {w}")
    print(f"Logged #{row['id']}: {row['date']} {row['dir']} {row['party']} — "
          f"{row['doc']}")
    for c in changed:
        print(f"  {c}")
    render(root, quiet=True)
    return 0


def apply_change(row, field, new, ts):
    old = row.get(field, "")
    if old == new:
        return False
    row.setdefault("history", []).append(
        {"field": field, "from": old, "to": new, "on": ts})
    row[field] = new
    return True


def cmd_set(root, args):
    """Update a row's status, action, due, note, or a pending path — the fields
    that legitimately change after the event. Every change is recorded in the
    row's history."""
    rows = load(root)
    known = by_id(rows)
    if args.id not in known:
        sys.exit(f"No event #{args.id} in {JSONL}.")
    row = known[args.id]
    problems, changes = [], []
    if args.status is not None:
        if not STATUS_RE.match(args.status):
            problems.append(f"--status must be {STATUS_HELP} — got "
                            f"'{args.status}'")
        problems += [f"--status cites {d}, which does not exist"
                     for d in dangling(args.status, known)]
        changes.append(("status", args.status))
    if args.action is not None:
        if not ACTION_RE.match(args.action):
            problems.append(f"--action must be {ACTION_HELP} — got "
                            f"'{args.action}'")
        problems += [f"--action cites {d}, which does not exist"
                     for d in dangling(args.action, known)]
        changes.append(("action", args.action))
    if args.due is not None:
        if args.due and not valid_date(args.due):
            problems.append(f"--due must be a real ISO date, got '{args.due}'")
        changes.append(("due", args.due))
    if args.path is not None:
        path = norm_path(args.path)
        if row.get("path"):
            problems.append(f"#{args.id} already has a path "
                            f"('{row['path']}'). A path is fixed once set; a "
                            f"row filed against the wrong file is corrected by "
                            f"a new row with a note.")
        elif not path:
            problems.append("--path is empty")
        else:
            problems += path_problems(root, path, row.get("dir"),
                                      row.get("party"))
            changes.append(("path", path))
    if args.note is not None:
        old = row.get("note") or ""
        changes.append(("note", f"{old} | {args.note}" if old else args.note))
    if problems:
        sys.exit("Cannot update #%d — nothing was written:\n  " % args.id
                 + "\n  ".join(problems))
    if not changes:
        sys.exit("Nothing to change: pass --status, --action, --due, --path "
                 "or --note.")
    ts = now_ts()
    applied = [f for f, v in changes if apply_change(row, f, v, ts)]
    if not applied:
        print(f"#{row['id']} unchanged — already as requested.")
        return 0
    write_all(root, rows)
    print(f"#{row['id']} → " + ", ".join(
        f"{f} '{row.get(f, '')}'" for f in applied))
    return render(root, quiet=True)


def matches(row, args, today):
    def eq(field, wanted):
        return wanted is None or (row.get(field) or "").lower() == wanted.lower()

    if not (eq("dir", args.dir) and eq("party", args.party)
            and eq("type", args.type) and eq("thread", args.thread)
            and eq("status", args.status) and eq("action", args.action)):
        return False
    if args.since and (row.get("date") or "") < args.since:
        return False
    if args.until and (row.get("date") or "") > args.until:
        return False
    if args.overdue and not ((row.get("action") or "") == "open"
                             and row.get("due") and row["due"] < today):
        return False
    if args.grep:
        blob = " ".join(str(row.get(k, "")) for k in FIELDS
                        if k != "history").lower()
        if args.grep.lower() not in blob:
            return False
    return True


def cmd_query(root, args):
    today = _date.today().isoformat()
    rows = sorted((r for r in load(root) if matches(r, args, today)),
                  key=lambda r: (r.get("date", ""), row_id(r)))
    if args.json:
        print(json.dumps(rows, ensure_ascii=False, indent=1))
        return 0
    if not rows:
        print("No matching events.")
        return 0
    for r in rows:
        print(f"#{r.get('id'):<4} {r.get('date', ''):<11} "
              f"{(r.get('dir') or ''):<4} {(r.get('party') or ''):<20.20} "
              f"{(r.get('type') or ''):<12.12} {(r.get('doc') or ''):<40.40} "
              f"{status_cell(r)}")
        if args.paths and r.get("path"):
            print(f"      {r['path']}")
    print(f"\n{len(rows)} event(s).")
    return 0


def tree_files(root, zone):
    base = os.path.join(root, zone)
    if not os.path.isdir(base):
        return
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in sorted(filenames):
            if (fn.startswith(SKIP_PREFIXES) or fn in SKIP_NAMES
                    or fn.lower().endswith(SKIP_SUFFIXES)):
                continue
            full = os.path.join(dirpath, fn)
            if os.path.isfile(full):
                yield os.path.relpath(full, root).replace(os.sep, "/")


def cmd_check(root, args):
    """The log against the tree, and against itself."""
    rows = load(root)
    findings = []
    ids = [row_id(r) for r in rows]
    for d in sorted({i for i in ids if ids.count(i) > 1}):
        findings.append(("DUPLICATE ID", f"#{d} appears {ids.count(d)} times — "
                         f"two writers appended at once. Renumber the later "
                         f"one by hand and fix every citation of it."))
    known = set(ids)
    labels = party_labels(root)
    today = _date.today().isoformat()
    logged_paths, logged_dirs = set(), set()
    for r in rows:
        rid = f"#{r.get('id')}"
        if not valid_date(r.get("date")):
            findings.append(("BAD DATE", f"{rid} date '{r.get('date')}'"))
        if not STATUS_RE.match(r.get("status") or ""):
            findings.append(("BAD STATUS", f"{rid} status '{r.get('status')}'"))
        if not ACTION_RE.match(r.get("action") or ""):
            findings.append(("BAD ACTION", f"{rid} action '{r.get('action')}'"))
        for field in ("status", "action"):
            for d in dangling(r.get(field), known):
                findings.append(("DANGLING", f"{rid} {field} "
                                 f"'{r.get(field)}' cites {d}, which does not "
                                 f"exist"))
        p = r.get("path") or ""
        if p:
            full = os.path.join(root, p)
            if not os.path.exists(full):
                findings.append(("PATH MISSING", f"{rid} → {p}"))
            elif os.path.isdir(full):
                logged_dirs.add(p.rstrip("/") + "/")
            else:
                logged_paths.add(p)
            for problem in path_problems(root, p, r.get("dir"), r.get("party"),
                                         pending=True):
                findings.append(("ROW/TREE DISAGREE", f"{rid}: {problem}"))
        else:
            findings.append(("NO PATH", f"{rid} {r.get('date')} {r.get('dir')} "
                             f"{r.get('party')} — {r.get('doc')} (pending; "
                             f"fill with `set {r.get('id')} --path`)"))
        if labels is not None and (r.get("party") or "") not in labels:
            findings.append(("UNKNOWN PARTY", f"{rid} party '{r.get('party')}' "
                             f"is not a label in {PARTIES}"))
        if ((r.get("action") or "") == "open" and r.get("due")
                and r["due"] < today):
            findings.append(("OVERDUE", f"{rid} due {r['due']} — {r.get('dir')} "
                             f"{r.get('party')}: {r.get('doc')}"))
    # A logged path covers itself, everything under it if it is a folder, and
    # any sibling under the same stem — the source document filed beside an
    # issued PDF at the same revision (R10) is part of that one event.
    logged_stems = {os.path.splitext(p)[0] for p in logged_paths}
    for zone in LOGGED_ZONES:
        for rel in tree_files(root, zone):
            if (rel in logged_paths
                    or os.path.splitext(rel)[0] in logged_stems
                    or any(rel.startswith(d) for d in logged_dirs)):
                continue
            findings.append(("UNLOGGED", f"{rel} — in a logged zone with no "
                             f"row; ingest it (R3) or it is invisible to every "
                             f"query"))

    if not findings:
        print(f"Log is consistent — {len(rows)} event(s), every path resolves, "
              f"every logged zone accounted for.")
        return 0
    groups = {}
    for kind, text in findings:
        groups.setdefault(kind, []).append(text)
    for kind in groups:
        print(f"{kind} ({len(groups[kind])}):")
        for text in groups[kind]:
            print(f"  {text}")
        print()
    print(f"{len(findings)} finding(s). None of these are fixed by editing "
          f"LOG.jsonl by hand: file, log or `set` as each line says.")
    return 1


# --------------------------------------------------------------------------
# entry
# --------------------------------------------------------------------------

def parse_args(argv=None):
    ap = argparse.ArgumentParser(
        description="Append to, query, check and render the exchange log (R4).")
    ap.add_argument("--root", help="repo root (default: this script's parent's parent)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="append one event")
    a.add_argument("--date", required=True,
                   help="ISO date of the event itself — never guessed")
    a.add_argument("--dir", required=True, choices=DIRECTIONS,
                   help="in = received, out = issued")
    a.add_argument("--party", required=True, help="counterparty label, per PARTIES.md")
    a.add_argument("--doc", required=True, help="what the document is")
    a.add_argument("--path", default="",
                   help="repo-relative path to the filed document (or the folder "
                        "of a multi-file event); for an issued document, the PDF")
    a.add_argument("--pending", action="store_true",
                   help="the file has not landed yet: allow an empty or "
                        "not-yet-existing --path, to be filled with `set --path`")
    a.add_argument("--type", default="", help=f"one of: {', '.join(KNOWN_TYPES)}")
    a.add_argument("--ref", default="", help="the document's own number, or how it arrived")
    a.add_argument("--rev", default="", help="sender's revision")
    a.add_argument("--thread", default="", help="topic, matching a context md")
    a.add_argument("--status", default="current", help=f"document state: {STATUS_HELP}")
    a.add_argument("--action", default="", help=f"what is owed: {ACTION_HELP}")
    a.add_argument("--due", default="", help="ISO date the open action is due")
    a.add_argument("--note", default="", help="anything that fits no column")
    a.add_argument("--supersedes", type=int, metavar="ID",
                   help="mark an earlier event superseded by this one")
    a.add_argument("--answers", type=int, metavar="ID",
                   help="mark an earlier open event answered by this one")
    a.add_argument("--backfilled", action="store_true",
                   help="this row is written after the fact, from the documents")

    s = sub.add_parser("set", help="update status/action/due/note, or fill a pending path")
    s.add_argument("id", type=int)
    s.add_argument("--status", help=STATUS_HELP)
    s.add_argument("--action", help=ACTION_HELP)
    s.add_argument("--due", help="ISO date, or '' to clear")
    s.add_argument("--path", help="fill the path of a --pending row")
    s.add_argument("--note", help="appended to the existing note")

    q = sub.add_parser("query", help="filter the log")
    q.add_argument("--dir", choices=DIRECTIONS)
    q.add_argument("--party")
    q.add_argument("--type")
    q.add_argument("--thread")
    q.add_argument("--status")
    q.add_argument("--action")
    q.add_argument("--since", help="ISO date, inclusive")
    q.add_argument("--until", help="ISO date, inclusive")
    q.add_argument("--overdue", action="store_true", help="open and past due")
    q.add_argument("--grep", help="substring across every field")
    q.add_argument("--paths", action="store_true", help="print each file path too")
    q.add_argument("--json", action="store_true", help="emit JSON, not a table")

    sub.add_parser("check", help="the log against the tree: gaps, dangling refs, drift")
    sub.add_parser("render", help="rewrite LOG.md from LOG.jsonl")
    return ap.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    root = repo_root(args.root)
    if not os.path.isdir(root):
        sys.exit(f"Repo root not found: {root}")
    if args.cmd == "add":
        return cmd_add(root, args)
    if args.cmd == "set":
        return cmd_set(root, args)
    if args.cmd == "query":
        return cmd_query(root, args)
    if args.cmd == "check":
        return cmd_check(root, args)
    return render(root)


if __name__ == "__main__":
    sys.exit(main())
